---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: lint-charts
    pull: default
    image: ranchercharts/chart-testing:v2.0.2-rancher3
    commands:
      - git remote add dev-charts https://github.com/cnrancher/dev-charts
      - git fetch dev-charts master
      - ct lint --config test/ct.yaml